KOE-138 take 2
koekalenteri/koekalenteri pull request #27
Opened 2021-11-02 19:58 UTC by kurkle

* Vähän puuhastelua pohjalla, nimetyillä exporteilla kaikki, käyttämättömät komponentit mäelle, ...

![image](https://user-images.githubusercontent.com/27971921/139942821-86f759ae-b536-4ee2-8608-fdcaf69523cd.png)

2021-11-03 08:26 UTC, rmiraftabi requested changes

2021-11-03 08:26 UTC, rmiraftabi commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +    return 'black';
Jos CSSää on pakko sotkea koodin sekaan niin ainakin värit jne kaikki muuttujien taakse jotka on koko UIlle globaaleja ja voidaan helposti muuttaa yhdestä paikasta. Mieluummin toki niin että koodissa pakotetaan vain jokin luokka päälle ja CSS:n puolella hanskataan loput.

2021-11-03 08:26 UTC, rmiraftabi commented on koekalenteri-frontend/src/components/utils.ts
> +  return format(date, 'eeeeee d.M.', { locale: fi });
Lokaalin kovakoodaus pois ja otetaan se jostain lokaali/kieliattribuutista. Kuitenkin jos speksi on että pitää voida kääntää softa. Toki päivämääräformaattia tuskin halutaan muuttaa jenkkimuotoon, mutta silti tämäkin jonnekin muuttujan tms taakse.

2021-11-03 09:41 UTC, kurkle commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +    return 'black';
vaihdoin teemaväreiksi

2021-11-03 09:43 UTC, kurkle commented on koekalenteri-frontend/src/components/utils.ts
> +  return format(date, 'eeeeee d.M.', { locale: fi });
Pitää polkasta lokalisointi siis tulille. Teen eri branchiin, jatketaan tätä sitten kun se on selvä.

2021-11-03 09:50 UTC, rmiraftabi approved these changes

2021-11-04 07:37 UTC, kurkle commented
Tämähän ei edelleenkään ole millään muotoa finaalissa, mutta baby steps :)
![image](https://user-images.githubusercontent.com/27971921/140274802-6ecf9b57-64bb-4836-93cc-a4d2ec7b299e.png)

2021-11-04 08:43 UTC, rmiraftabi requested changes

2021-11-04 08:43 UTC, rmiraftabi commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +const entryDateColor = (event: EventEx) => event.isEntryOpen ? event.isEntryClosing ? 'orange' : 'green' : 'black';
Taas on värejä koodissa eikä teemaa tms.

2021-11-04 08:51 UTC, kurkle commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +const entryDateColor = (event: EventEx) => event.isEntryOpen ? event.isEntryClosing ? 'orange' : 'green' : 'black';
aina ne toiset silmät on hyvät, rebasessa särin.

2021-11-04 08:54 UTC, kurkle commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +const entryDateColor = (event: EventEx) => event.isEntryOpen ? event.isEntryClosing ? 'orange' : 'green' : 'black';
eikäku ei, on ne fiksattu, myöhemmässä kommitissa

2021-11-04 08:57 UTC, rmiraftabi commented on koekalenteri-frontend/src/components/EventInfo.tsx
> +const entryDateColor = (event: EventEx) => event.isEntryOpen ? event.isEntryClosing ? 'orange' : 'green' : 'black';
Miulla github näyttää nyt nuo committien ajat ihan hämärästi...

2021-11-04 08:58 UTC, rmiraftabi approved these changes

2021-11-04 11:56 UTC, merged