Front end aole first try
koekalenteri/koekalenteri pull request #6
Opened 2021-04-21 06:11 UTC by aolenia

Some dummy UI components.

2021-04-21 07:08 UTC, kurkle requested changes
* Linttifiksit `npm run lint -- --fix`
* Melkeen kaikki noi palikat (pl. EventText) vois asua sielä layout kansiosssa.

2021-04-21 13:32 UTC, kurkle reviewed
Testiksi vois laittaa vaikka tommosen, joka ehkä vois olla ihan pysyvä:
```ts
test('renders logo with proper ALT', () => {
  render(<App />);
  const imgElement = screen.getByAltText('Suomen noutajakoirajärjestö');
  expect(imgElement).toBeInTheDocument();
});
```

2021-04-21 13:32 UTC, kurkle commented on src/koekalenteri-frontend/src/components/EventText.tsx
> +          <ListItem button>
```suggestion
          <ListItem button key={event.id}>
```

2021-04-21 18:11 UTC, kurkle approved these changes

2021-04-22 05:10 UTC, rmiraftabi approved these changes

2021-04-22 05:36 UTC, merged